project_id = "xucoadixeyuowowcrkwg"

[functions.data-commons]
verify_jwt = false

[functions.ai-analyze]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.chat-data]
verify_jwt = false

[functions.daily-report]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-test-report]
verify_jwt = false
